#!/bin/sh

# variables
INVIDIOUS_INSTANCE="https://vid.puffyan.us" # some instances might not work

# stop current song, clear playlist
mpc stop
mpc clear

# make youtube search query
query="$(printf '%s' "song audio $1" | tr ' ' '+' )"

# search on invidous (youtube) instance for video id to make a url
video_id="$(curl -s "$INVIDIOUS_INSTANCE/search?q=$query" | grep -Eo "watch\?v=.{11}" | head -n 1)"
youtube_url="https://youtube.com/$video_id"

# get url for bestaudio stream from the youtube video
audio_url="$(yt-dlp -f bestaudio --get-url "$youtube_url")"

# add the track to mpd and play
mpc add "$audio_url"
mpc play

# Get youtube video title for system notification
title=$(yt-dlp --get-title "$youtube_url")
notify-send "Playing: " "$title"